### ISSUE TITLE
Better Tables!

### ISSUE THREAD

**Issue by the-alex** [MichiganDataScienceTeam/MichiganDataScienceTeam.github.io#6]
The table styling could be better. Something more like the GitHub ones would be nice.

Example:

| Tables | Are | Cool |
| --- | :-: | --: |
| col 3 is | right-aligned | $1600 |
| col 2 is | centered | $12 |
| zebra stripes | are neat | $1 |

Off the top of my head, starting with something as simple as ...

``` css
td {
    border-width: 1px;
    border: solid 2px black;
    padding: 10px 10px 10px 10px;
}
```

... wouldn't be too bad.
